In [11]:
import pandas as pd
from openpyxl import load_workbook

file = "user-data.xlsx"

name = str(input("Enter name: "))
phone = str(input("Enter phone number: "))
email = str(input("Enter email: "))
password = str(input("Create a password: "))

workbook = load_workbook(file)
sheet = workbook.active

data = [email, phone, password, name]

sheet.append(data)
workbook.save(file)

print("User data added successfully!")

df = pd.read_excel(file)
df

User data added successfully!

              email       phone   password      name
0        cutm@email  9078741119        123    subham
1  hello@google.com   907856432     hi6655  mohammad
2    raju@gmail.com   786949123  hello3000      raju

In [15]:
import pandas as pd
file = "user-data.xlsx"
df = pd.read_excel(file)

email1 = str(input("Enter email: "))
val = df['email'] == email1

 
if val.any() == True:

    password1 = str(input("Enter your password: "))
    pas = df.loc[df['email'] == email1, "password"]
    pas1 = pas.iloc[0]

    if pas1 == password1:
        print("Password matched")
    else:
        print("Incorrect password")


elif val.any() == False:
    print("Email not found try again")

Password matched

In [17]:
# MERCHANT

import pandas as pd
from openpyxl import load_workbook

file = "merchant_data.xlsx"

name = str(input("Enter name: "))
phone = str(input("Enter phone number: "))
email = str(input("Enter email: "))
password = str(input("Create a password: "))
business_name = str(input("What is the name of your business? : "))

workbook = load_workbook(file)
sheet = workbook.active

data = [email, phone, password, name, business_name]

sheet.append(data)
workbook.save(file)

print("User data added successfully!")

df = pd.read_excel(file)
df

User data added successfully!

            email  phone password  name business_name
0  yes.wow@ya.com   8970     123#  runa     pani puri

In [ ]:
#MERCHANT LOGIN

import pandas as pd
file = "merchant_data.xlsx"
df = pd.read_excel(file)

email1 = str(input("Enter email: "))
val = df['email'] == email1

 
if val.any() == True:

    password1 = str(input("Enter your password: "))
    pas = df.loc[df['email'] == email1, "password"]
    pas1 = pas.iloc[0]

    if pas1 == password1:
        print("Password matched")
    else:
        print("Incorrect password")


elif val.any() == False:
    print("Email not found try again")

Password matched